##################CPJES2IN===================
  TTLSEnvironmentAction ECPJES2IN
  {
   HandshakeRole Server
   TTLSEnvironmentAdvancedParms
   {
    ApplicationControlled On
    TLSv1   Off
    TLSv1.1 Off
    TLSv1.2 On
    TLSv1.3 On
    SSLV3   Off
   }
   TTLSKeyringParms
   {
    Keyring SYSTEM/TELNET_RING
   }
  TTLSCipherParms
    {
      V3CipherSuites TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      V3CipherSuites TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      V3CipherSuites TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      V3CipherSuites TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      V3CipherSuites TLS_AES_128_GCM_SHA256
      V3CipherSuites TLS_AES_256_GCM_SHA384
      V3CipherSuites TLS_CHACHA20_POLY1305_SHA256
    }
  }
  TTLSGroupAction GCPJES2IN
  {
   TTLSEnabled On
   Trace 255
  }
  TTLSRule CPJES2IN
  {
   Priority 255
   LocalAddr ALL
   RemoteAddr ALL
   LocalPortRange 2252
   Direction Inbound
   TTLSEnvironmentActionRef ECPJES2IN
   TTLSGroupActionRef GCPJES2IN
  }
##################CPJES2OUT===================
  TTLSEnvironmentAction ECPJES2OUT
  {
   HandshakeRole Client
   TTLSEnvironmentAdvancedParms
   {
    ApplicationControlled On
    TLSv1   Off
    TLSv1.1 Off
    TLSv1.2 On
    TLSv1.3 On
    SSLV3   Off
   }
   TTLSKeyringParms
   {
    Keyring SYSTEM/TELNET_RING
   }
  TTLSCipherParms
    {
      V3CipherSuites TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      V3CipherSuites TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      V3CipherSuites TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      V3CipherSuites TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      V3CipherSuites TLS_AES_128_GCM_SHA256
      V3CipherSuites TLS_AES_256_GCM_SHA384
      V3CipherSuites TLS_CHACHA20_POLY1305_SHA256
    }
  }
  TTLSGroupAction GCPJES2OUT
  {
   TTLSEnabled On
#   Trace 255
  }
  TTLSRule CPJES2OUT
  {
   Priority 255
   RemoteAddr ALL
   RemotePortRange 2175-2175
   Direction Outbound
   TTLSEnvironmentActionRef ECPJES2OUT
   TTLSGroupActionRef GCPJES2OUT
  }
